# Generated by Django 3.1.3 on 2020-12-09 05:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CoreApp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='addamount',
            name='category',
        ),
        migrations.RemoveField(
            model_name='addexpense',
            name='category',
        ),
    ]
