# Generated by Django 3.1.3 on 2020-12-09 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CoreApp', '0003_auto_20201209_1101'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addamount',
            name='description',
            field=models.TextField(blank=True, default='No Description', null=True),
        ),
    ]
