# Generated by Django 3.1.3 on 2020-12-09 13:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CoreApp', '0005_remove_addamount_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='addexpense',
            name='description',
        ),
    ]
