# Generated by Django 3.1.4 on 2021-01-13 10:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('CoreApp', '0009_auto_20210112_1946'),
    ]

    operations = [
        migrations.CreateModel(
            name='Graph',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('expense', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CoreApp.addexpense')),
                ('income', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CoreApp.addamount')),
            ],
        ),
        migrations.DeleteModel(
            name='Customer',
        ),
    ]
